- azdev/help.py
- azdev/operations/pypi.py
- azdev/params.py
Closes #31.
New usage:
- `azdev verify version --update` - will verify local versions against PyPI AND update setup.py with the current versions. This would be run on the release branch to bump necessary module versions and ensure setup.py for azure-cli reflects those versions.
- `azdev verify version <MOD>` - will verify local versions against PyPI but do nothing with azure-cli setup.py file.
- `azdev verify version` - will verify local versions against PyPI and audit local versions against the azure-cli setup.py file. This would be run as a precheck in the publish phase.
> Add ability to audit/update azure-cli setup.py in `azdev verify version` command

- azdev/operations/pypi.py
- azdev/operations/style.py
- setup.py
- Add missing package for linter.
- Fix up history verification for CI mode.
- Allow pep8 to run without CLI. Require only if running pylint.
- Fix #21 (hopefully)
> Small fixes to support running from Travis CI

- azdev/commands.py
- azdev/help.py
- azdev/operations/linter/__init__.py
- azdev/operations/linter/linter.py
- azdev/operations/linter/util.py
- azdev/operations/performance.py
- azdev/operations/pypi.py
- azdev/operations/tests/__init__.py
- azdev/params.py
- setup.py
Work in progress.
- Standardizes behavior so `azdev test/style/linter` will, if nothing is provided, run on everything. Previously `azdev test` would not run any tests.
- Fix issue where `ci_exclusions.yml` were not found for the linter in CI mode.
- Splits `azdev verify version` into `azdev cli check-versions` and the much faster `azdev cli update-setup`. These will be used on the release branch. There are convenience argumetns in check-versions to effectively do the setup.py update without running an extra command.
- The check-version and update-setup commands allow you to let the versions in setup.py be pinned or unpinned.
- Fix #14. The module loading perf script now allows a certain number of modules to reach specific thresholds. This should avoid spurious CI failures.
> Azdev Fixes to work with Azure-CLI CI

- tox.ini
The latest build in `master` (947200c) and #50 #46 look like they're both running into CI issues.
> Disable pylint until InvocationErrors are sorted out

- .gitignore
- azdev/operations/linter/rules/help_rules.py
See https://github.com/Azure/azure-cli/pull/8608
Allow parameter values that contain 'az' or pipes '|'. 
Lint nested commands.
Skip unsupported examples.
> Linter Rule Updates. 

- azdev/operations/tests/__init__.py
- setup.py
Fixes #45.
Fix issue where virtual env in the extensions directory would could a stack trace on test discovery.
> Fix `azdev test --discover`

- .gitignore
- azdev/commands.py
- azdev/config/ext.flake8
- azdev/help.py
- azdev/operations/extensions/__init__.py
- azdev/operations/extensions/util.py
- azdev/operations/setup.py
- azdev/operations/style.py
- azdev/operations/tests/__init__.py
- azdev/params.py
- azdev/utilities/__init__.py
- azdev/utilities/command.py
- azdev/utilities/config.py
- azdev/utilities/path.py
- setup.py
Closes #58.  The user can configure defaults for the storage account, container and subscription.
```
(env) Traviss-MacBook-Pro-2:github travisprescott$ azdev extension publish -h
Command
azdev extension publish : Build and publish an extension to a storage account.
Arguments
--dist-dir             : Name of a directory in which to save the resulting WHL files.  Default:
dist.
--update-index         : Update the index.json file after publishing is complete.
--yes -y               : Answer "yes" to all prompts.
Positional
NAME                   : Space-separated list of extension names.
Storage Arguments
--storage-account      : Name of the storage account to publish to.
--storage-container    : Name of the storage container to publish to.
--storage-subscription : Subscription ID of the …
```
> Add `azdev extension build` and `publish` commands.

- setup.py
Fix #77.
Bump to ~=4.4.0 since this is what pytest-xdist requires.
> Bump min pytest version

- azdev/operations/pypi.py
Update error parsing due to change in pip command error format.
> Fix `azdev cli check-versions`

- azdev/utilities/path.py
Previously, simple modules like `profile` that lacked a `commands.py` file would not discover any tests.
> Fix test discovery for simpler command modules.

- azdev/operations/setup.py
This will ensure that folks doing development have the same version of the dependencies on their local machines that we will eventually distribute the CLI with.
> Update setup command to use platform appropriate requirements.txt file.

- azdev/params.py
- azdev/utilities/path.py
* Optimize help message of linter
* Add another warning for command runing on a wheel installed extension without --include-whl-extensions
* Clean code
* Partially fix https://github.com/Azure/azure-cli/issues/11140
* Partially fix https://github.com/Azure/azure-cli-extensions/issues/1078
> Add reasonable warning when command on wheel extentions without --include-whl-extensions

- azdev/operations/extensions/__init__.py
Resolves #155
- Looks for `{` when publishing to find the JSON response to determine if blob already exists
- Looks for **https** when updating **index.json** to ensure only the URL is evaluated
> [Extension] Resolves issue where warning is emitted when update index

- azdev/operations/extensions/__init__.py
- azdev/params.py
- azure-pipelines.yml
- setup.py
There are two changes here:
1. Use sdk in azure-storage-blob toimplement "azdev extension publish"
2. Add an additional argument --storage-account-key
Previous behavior is that we query key for users.
> azdev extension publish: Add one more argument storage account key

- setup.py
The lock on knack version causes problem once Azure CLI starts using knack 0.7.0rc1 
https://github.com/microsoft/knack/pull/185
https://github.com/Azure/azure-cli/pull/12604
```
(env38) PS D:\cli> azdev setup -c azure-cli -r azure-cli-extensions
Traceback (most recent call last):
File "D:\cli\env38\Scripts\azdev-script.py", line 6, in <module>
from pkg_resources import load_entry_point
File "d:\cli\env38\lib\site-packages\pkg_resources\__init__.py", line 3099, in <module>
def _initialize_master_working_set():
File "d:\cli\env38\lib\site-packages\pkg_resources\__init__.py", line 3082, in _call_aside
f(*args, **kwargs)
File "d:\cli\env38\lib\site-packages\pkg_resources\__init__.py", line 3111, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File …
```
> Remove knack version lock

- setup.cfg
Same as https://github.com/Azure/azure-cli/pull/12683
Remove `universal=1` so that PyPI doesn't mark the package as Python 2 supported: 
https://pypi.org/project/azdev/#files
azdev-0.1.10-py2.py3-none-any.whl (80.3 kB) | Wheel | py2.py3
-- | -- | --
> Remove py2 wheel bdist

- azdev/operations/extensions/__init__.py
When `if not yes` condition is not satisfied, the following error will occur:
```
local variable 'client' referenced before assignment
```
> [extension] Fix issue if --yes is not provided while publish extension

- README.md
On windows the path is usually ` env\Scripts\`  and not `env\scripts\` from my experience.
> [Document] Update windows virtual env activation path

- azdev/help.py
- azdev/operations/tests/__init__.py
- azdev/operations/tests/incremental_strategy.py
- azdev/operations/tests/profile_context.py
- azdev/operations/tests/pytest_runner.py
- azdev/operations/tests/tests/__init__.py
- azdev/operations/tests/tests/test_profile_context.py
- azdev/params.py
- azdev/utilities/git_util.py
- setup.py
1. Refine the logic of testing against different profiles with `ProfileContext`
2. pytest version limit change to `pytest>=4.4.0`
3. Use `AzureDevOpsContext` to apply incremental test strategy.
4. Refine the main flow of `azdev test` to be more compact and clean
To apply incremental test logic on Azure CLI test:
```Shell
if [[ "$PULL_REQUEST_TARGET_BRANCH" != "System.PullRequestTargetBrancg" ]]; then
azdev test --series --repo=./ --src=HEAD --tgt="$PULL_REQUEST_TARGET_BRANCH" --cli-ci --profile "$TARGET_PROFILE"
else
azdev test --series  # will run all tests
fi
```
Listed https://github.com/Azure/azure-cli-dev-tools/pull/188
> Enable azdev for Azure/azure-cli CI automation test

- azdev/help.py
- azdev/operations/linter/__init__.py
- azdev/operations/setup.py
- azdev/params.py
Development part to solve https://github.com/Azure/azure-cli/issues/9781. 
This PR adds `--deps-from` option to `azev setup`. By default, use the `requirements.*.txt` file to resolve dependencies for Azure CLI project. Specify `--deps-from setup.py` to use `setup.py` files to resolve dependencies, which is the previous behavior.
> Add --deps-from to azdev setup and use requirements file to resolve dependencies by default

- azdev/operations/linter/rules/parameter_rules.py
We may need to rethink about this rule. We already met two teams want to pass this rule. Except for `--resource-group-name`, there are some commands need extra resource group parameter.
https://github.com/Azure/azure-cli/pull/14027 destination_resource_group
https://github.com/Azure/azure-cli-extensions/pull/1709 service_runtime_network_resource_group
> Downgrade parameter_should_not_end_in_resource_group's severity to Medium

- .pylintrc
- azdev/config/cli_pylintrc
- setup.py
Same as https://github.com/microsoft/knack/pull/216
`wrong-import-order` is disabled due to https://github.com/PyCQA/pylint/issues/2175, https://github.com/PyCQA/pylint/issues/1797
Otherwise will get error:
```
> pylint azdev --rcfile=.pylintrc -r n
************* Module azdev.operations.help
azdev\operations\help\__init__.py:20:0: C0411: third party import "from azure.cli.core.extension.operations import list_available_extensions, list_extensions as list_cli_extensions" should be placed before "from knack.util import CLIError" (wrong-import-order)
************* Module azdev.operations.help.refdoc.extension_docs.helpgen
azdev\operations\help\refdoc\extension_docs\helpgen.py:9:0: C0411: third party import "from azure.cli.core.file_util import _store_parsers, _is_group" should be placed …
```
> Update Pylint to 2.5.3

- setup.py
Pin `isort` and revert `pylint` update (https://github.com/Azure/azure-cli-dev-tools/pull/224).
No matter whether we use the **`main` branch of `azdev`** or the **released version on PyPI**, `pylint` will crash with `AttributeError: module 'isort' has no attribute 'SortImports'`, but `azdev` can't detect that (another bug). In such case, `pylint` doesn't work at all, giving a false positive indicating the style check passed.
> Pin isort and revert pylint

- azdev/operations/style.py
- azdev/operations/tests/__init__.py
- azdev/operations/tests/test_style.py
Fix https://github.com/Azure/azure-cli-dev-tools/issues/209
> Hornor flake and pylint settings of CLI and Extensions repo

- .coveragerc
- azure-pipelines.yml
The current report contains analytics of azure-cli and azure-cli-extensions as their code source is placed under --cov=. 
- Remove it
- Ignore analytics on test code.
> Refine ADO coverage report output

- azdev/operations/linter/__init__.py
- azdev/operations/linter/linter.py
- azdev/operations/linter/rule_decorators.py
Two changes
- Only violation of high severity would exit with 1.
- No module selected would exit with 0 instead of CLIError.
> [Linter] Only violation of high severity would exit with 1

- setup.py
Fix https://github.com/Azure/azure-cli-dev-tools/issues/211.
pytest 5.0.0 is the minial version to make test pass on Windows
> pytest greater than 5.0.0

- azdev/operations/linter/linter.py
- azdev/operations/linter/rules/parameter_rules.py
- param's length cannot exceed 22
- param's name should not have `_`
> [Linter] Param's length cannot exceed 22 and name should not use `_`

- azdev/operations/testtool/__init__.py
- azdev/operations/testtool/pytest_runner.py
- azdev/params.py
- azdev/utilities/command.py
Select tests with this mark. You can add @pytest.mark.custom_mark to a test
The old code has a bug. It does not support quotes. Quotes are necessary when the value contains space.
I have tested in both Windows and Linux.
> Support --mark; Fix a bug of invoking external comand

- azdev/operations/tests/test_benchmark.py
The incorrect mocking way cause confusing import status that blocks https://github.com/Azure/azure-cli-dev-tools/pull/254
> fix incorrect mocking way to unblock

- azure-pipelines.yml
- setup.py
Support Python 3.9.
Only Tox test is updated to 3.9 as other tests rely on Azure CLI which hasn't supported Python 3.9 yet.
Add Python 3.7 tests to help identify issues that [starts since/only exits in] Python 3.7 (https://github.com/Azure/azure-cli/pull/16634).
> Support Python 3.9

- azdev/help.py
- azdev/operations/setup.py
- azdev/utilities/__init__.py
- azdev/utilities/command.py
The current `azdev setup` silences any error that happens. This leads to difficulties in troubleshooting installation dependencies (https://github.com/Azure/azure-cli-dev-tools/pull/274, https://github.com/Azure/azure-cli/pull/16655, https://github.com/Azure/azure-cli/issues/16611).
- This PR lets `pip_cmd` raise `CommandError` by default if `pip` command fails. For other references of `pip_cmd`s, they assume that `pip_cmd` succeeds. Now in case of failure, bare exception `CommandError` is raised.
- `az setup` now supports `--verbose` to show the commands that are run, `--debug` to show the command output.
```
azdev setup -c --debug
=======================
| Azure CLI Dev Setup |
=======================
Azure CLI:
D:\cli\azure-cli
Installing packages
=====================
Upgrading pip... …
```
> azdev setup: show error if pip command fails

- azdev/__main__.py
- azdev/operations/code_gen.py
- azdev/operations/help/__init__.py
- azdev/operations/linter/linter.py
- azdev/utilities/display.py
- scripts/license_verify.py
Remove `from __future__ import print_function` which is used for Python 2 support.
> Remove `from __future__ import print_function`

- azdev/operations/extensions/__init__.py
- setup.py
In previous version, we fix azure-storage-blob < 2.0.0 because storage code is for track1 and with version >= 12.0.0, azure-storage-blob goes to track2 package, which is not compatible with current code. Here is to use azure-multiple-storage, which includes both track1 and track2 SDK to avoid the dependency for fixed azure-storage-blob.
> Change package dependency

- azdev/operations/code_gen.py
SDK has renamed version file from `version.py` to `_version.py`, which blocked vendor_sdk copy.
> fix _copy_vendored_sdk issue
